language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libexempi3

# command to install dependencies
install:
  - pip install coveralls
  - pip install .

# command to run tests
script:
  - coverage run setup.py test

after_success:
  - coveralls

notifications:
  email:
    - "john.g.evans.ne@gmail.com"
    - "lars@hankat.dk"
